name: deploy
jobs:
  deploy-degica:
    container:
      image: degica/rails-buildpack:2.4
      env:
        BARCELONA_ENDPOINT: https://barcelona.degica.com
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |-
        curl -L -o bcn.zip https://github.com/degica/barcelona-cli/releases/latest/download/bcn_linux_amd64.zip
        unzip ./bcn.zip && mv ./bcn /usr/bin/bcn
    - name: script
      run: bcn deploy -q -e production --tag $GITHUB_SHA --heritage-token ${{ secrets.MAINLINE_HERITAGE_TOKEN }}
'on':
  push:
    branches:
    - master
